language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- nosetests --with-coverage --cover-package=src
after_success:
- codecov
deploy:
  provider: heroku
  api_key:
    secure: mbG0uizf7/GawkoLZTAEEwBgmCMgIca2xxqHB7OOZm8TSzLZrkLK9gHXDKMs4HFKMt8B8EEAveCXQJ/5SCdg2spY4n33qYg9sS6gm9XRLoQ6FukzH/oZhfEbAs9Ht7JbSEvgyVUC1cpMBR2cHQoBvOJhDPxLjhSfsPRUR6RFc3C/HJ4XpNA9CpsWbgSuZHhHRikEjIcAlgVnAY+gQsG4/mZ8JXm0px2DEZSANy/nNzP7oRadtX5comnxY8eC+qUrcFX7aNYjW7KOYkgLb1Nn/4hPYjhQk5aSyoOXsFV5oU//KeKi/FTM9gzHnsFDQTvWfn+Kdhy6rqffQVN8xURv0Ja3fELPHHgspT9wkFHNYHCYX9cdzPhM/+7IfAbDbqUkAjY4WbTVBFqY9ZRZTW9myU+F0iNAAqnwzXGMk7Ss0oXlVGacTD1yypHZ+SqNoUhXjS2JSmbsDS0yz41NSqONhMq2Bc/Sb8qGVSeB5Vd3dCzkrs2CzzuEpA8yPGiKwgWTLjrWuIDKKciXgGrMU5vDg1iNeEmU6TJimUQe7DVWVQ6e0OeKtBilkKPR7YoqXk223FLO147oI3HS9+lkmIPK0HxNA6D9E3EzUm825W2pDPdFTCnjOIsIgNdtl2pQQdsrANGeAkCyC9GbhaykE3+b5vhDZOAF8WvKqqV8Zqz1fpo=
  app: villoro-devops
