language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- nosetests --with-coverage --cover-package=src
after_success:
- codecov
deploy:
  provider: heroku
  api_key:
    secure: "HwFjmvdg81c39MS8IRcXUDPKZ9xIFIthmszI8bcjVFbX/tP4WDTrcm0A4og/IvXzBkeSyi/lqB3sQlK01mqzuOcADSRLuwRiZJW/lDzpwf6CffHbBzAaPU1TAtANDA2bJp0cqYBC7Yf6aFrop1KGz5uBsaGtGIbw76kjz9fw9K+9uxwjDARkQg1GnXZxUc/T8Eaj2T26gcuXKnILHgkLwfxLc2zhVSX+UZMvY8ir2jW8ZagIOd9vgjJf0Gp5Dnx3pnOw8A7Sm3Y2C5/B6kO3fdhMdfKUlOmVMgL1YEFQT7KhNNwcLyI4D1jRRkOlY/pqaFlO6DgO3ThPnSvbOVpKMhaSKgxE23xTd9+aQmLjnL1d7ERdA2xXNz+Rx5yyU5tTrwmVLQ6sTB8pEnD4YM2rwf49KpqaVcfc/9UtKluBagKg44pFxcT+LMpzBUSV/9S1VcW8fNMs3zaeDxBTGG4FEzjONYlf42JoQC65Hb4nMeqASzlbGDA9DsKT0DiaDMSPvSt8oWZpVnhsyES9LafASx5o+0zj1gHstzKdId85aWZDTEOx1M8mWofW1f69iPK0Ch43s7xRhegVzIKg5YzUqRFWkNSlxR7fEsiVvfGdysIMHkGr2P7+jYcnlmTRwTt32P+CGUekN/aFSXJuDCZ/nGDMnX5a+rUGlL4wSPvw4+k="
  app: villoro-devops
