language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- nosetests --with-coverage --cover-package=src
after_success:
- codecov
deploy:
  provider: heroku
  api_key:
    secure: "Z/FiCNZXYB1OHa2fUIpS5XMgAzOo1pAwZlQeNDka4WqX9wZzV77LMIP2Ms009e1fqapaDatiZjm7yimUyKXca3oNLtYm/jZlThh/VPq/gzrll9hnt8SuEqn3OfLv4bRIbD/BX65k5po1N2on6BE3ZjOUArjAYbpfy4I2ujM5AHyNCDImJghPj9SwZ3wfqyUZj6p/cx0ef3Tnd/RNxP+wqy5vgpBAdAKm9MB0dFcVx3oy4c/s301950r5z9C4JoOba6wwYhhBKxE+tcbiWLRTiGzKiCJxmCbshNfUwiZvlTufE1GfM30drYxvTqEmaLfeof2+kveGUi8dikIug8pXPVYANc3ZQruzpcgM7/mcxJeqBriE2sVbSx+yKvX3zzn6LMfmVYN8wVutvwrCu4KNCUUicGkeI+rX3WJ8KmEsUzAUWh7Jys6QOT29ex8ca+Z2/bmvg3bhmwBCErz+mlcVkERbSorAVtNOmBz8DlB65v1IObPls5vV9xBb9wLy/MTbdrKmMIWtu72lvwBgR67bPzWhK+H9RF1JL0ez+9M04YOR05UmMEvGe/fvxlsicDzgzKKL1CXMt3G/F4M83WZzX1M06QDtIR5cV765ljGgl1BG//Jh5qVK5ri5Go22gb7yjrN1jBCVSG45GLmKjj1MaXpc2quRLZ9nL6Qe2k/1UWM="
  app: villoro-devops
