language: python

python:
- '3.6'

install:
- pip install -r requirements.txt
- pip install codecov
- pip install selenium==3.4.3

script:
- python src/index.py
- nosetests --with-coverage --cover-package=src

after_success:
- codecov
