language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- nosetests --with-coverage --cover-package=src
after_success:
- codecov
deploy:
  provider: heroku
  api_key:
    secure: iwuJtcUnPV5hMSgd1+l0UubFXCvADVmh6VKD+MrHqYtGMfiHdaVsHsOCNk7Uj8LNJWD86pcUuOAdOI4iuMojgIPa7U7cH3DJLrgZqTU9K47ghv2R2OfU+gmXUfAeqquCkqvAVhrA2i+58NsdrpUnwhmTl+bfLsC9/kGkpXUPbJKFcItff/rPrJwcwzNnVi7DbZ6pGE6XytaFDCFjYk498Dz5jmwDy7mG0PWtzkTFg01hcxVsPf5/vy2ntNNszRyBASORSg6Hu5OLSL01T7IARCN3GdO/Eq92KPLQL5dTMNjIrOYwQ24w/dut7WXZkPBLYtjEClfGSgWuoMwXfVfRn6FTzlazbHxwi+fMVoXKlc+GaiWsxMfmPb8g45L0iQenl8O5jX2Oy9br58miB3XKX6LxffbaBYBz9cBW0iQj4/PZj0+9/upSKiUlE7h4Id5kOR2Js4BnZhYvLRA1kN0ggOh6QCsNjdBcT2RXhkYnxERA0L2jEEIA5jqrjrRHuHIM3HiWKm0mY8e+3Ix/vIUzkaJdGnNMsvvjyKVuwqfd6G5SJPyu170WLv4pg3HiDxAzzGnaASF80LJoBD3gujo4UgkHC6tRHHgS6LTp68H8+whPYzGMj6SHFcjiLJBPcdla94GJGV8MAJp5DHfmWJWO0ECKInJcrLo7nQ/WBjUpQw8=
