language: python

python:
- '3.6'

install:
- pip install -r requirements.txt
- pip install codecov
- pip install selenium==3.4.3

before_script:
- "python src/index.py"

script:
- nosetests --with-coverage --cover-package=src

after_success:
- codecov
