language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- nosetests --with-coverage --cover-package=src
after_success:
- codecov
deploy:
  provider: heroku
  api_key: c5d50271-ef90-4e8e-8b47-eeae6cb0934d