sudo: required

addons:
  chrome: stable

language: python

python:
- '3.6'

install:
- pip install -r requirements.txt
- pip install codecov
- pip install selenium==3.4.3

before_script:
# Get chromedriver
- wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/
- export CHROME_BIN=chromium-browser

# Open dash app to test it
- "export DISPLAY=:99.0" #set up xvfb, req'd for webdriver/firefox
- "sh -e /etc/init.d/xvfb start"
- "python src/index.py&"
- "sleep 3"

script:
- nosetests --with-coverage --cover-package=src

after_success:
- codecov
