language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls pylint

script:
  - nosetests --with-coverage --cover-package=src

after_success:
  - coveralls
