sudo: required

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

language: python

python:
- '3.6'

install:
- pip install -r requirements.txt
- pip install codecov
- pip install selenium==3.4.3

before_script:
- "export DISPLAY=:99.0" #set up xvfb, req'd for webdriver/firefox
- "sh -e /etc/init.d/xvfb start"
- "python src/index.py&"
- "sleep 3"

script:
- nosetests --with-coverage --cover-package=src

after_success:
- codecov
