language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- nosetests --with-coverage --cover-package=src
after_success:
- codecov
deploy:
  provider: heroku
  api_key:
    secure: U0KOj13YT06uoHHAGOjaSvIsCCnTQbrih6TzesBcymjdNmkEff4cZbWqFaVVGjhj2+Obb+njsw09gSenYvyK/ukX5vLEBuVplnxTI3ETfZIxvwXiOZP0/nK/TbPsyd5bkiodLQaHUHxadiZUPKuxHysOpe6e+eODGoE0FOBfaf96pKmafV8Cd0TG26SBxOHF+fI4Izmy3inCs0iqBuQ9i21Eeny9nk+KUDan0jwIE71BdZE5OYkQXakemBcKnQvtUTHQlcn4ok5DdJXoLao1EnFn+lN/hhkingHMG2vpF3HOfmIKVQpQJqNy76WmSr2mb0j/uhXvTUgwKweQgkbfZmhybSlyJz6bQbDMF/FxWGTsS2lPEfkmM4TCla8mgAd5CTbTFVPQirArYuMV7RjkWgpPAa4q6JKNRNTqqirw08bsHIKa10NfOsH7yq7ceBe4y4/zZCNL20JLwLjx2R30+YhKxWzLVHCHf5axcI5KlSCcfgoDRi4N0wXYviZlrchZaWqlb6xQsjQ/9MsCEVGhUolDh6Yf54v9wRfU/TEn16FWcVzkVAC3Dgmz/CMvHjnp+b9CywD5oz2r84izEplTp6JtSaqkx8JKR5kY/sfRMW7eyfjDqvQrbUhH+UAX+AmXv/25xRqmV1CPrMinr310g+DN0sdc33aJTV8AhrRnt58=
  app: villoro-devops
  on:
    repo: villoro/devops
