language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- nosetests --with-coverage --cover-package=src
after_success:
- codecov
deploy:
  provider: heroku
  api_key:
    secure: "r0TdjdrPd/eegTC8gcJ2hIJ1GPMD4qWouweYI3cE3t8o22+zKJq+zqK2mnbTYuywakVQhUy2XyPHAzqwZiB4oc4InSk2FSHu+/7rPYXnSQhaw8aVeTgh3pbC1KRAjba+B2ent3Q4yZEJfSQdX3EuwGj12ZBRWwgWQMBQsfhQXpxuxF4LR+2AXLD3pcoxqEGva2ne3UcGilfutYqzt2FBMmbSbdam24bERwrumMjJowxGldB+1C3BO6jigFJf/eWRfl4YgTUtUBT0djHjf4HGhlxk7zwLF9kIXT+wvYFSiPFoU/1BMZzcgbyoafqbspB/wNy7QHwWAchUG0QromuvX6KtI53Uwb0Pa7zuQQXqdD70keqFc/uzBuolYiJLhBHpHs/J5Dx3gg+/TfpLWDu/aVvXZxOhU/6YzTSME6QgelFQcDZtpXOr7nVR4qUmDg7SgV8A2UpXWoh2qboLySXFO7TkCPbboqaST1jVkg6TI9WEIFbUrdlgDZFJGeScr06oXaM657Arg0hVBkYBB1sEK+4cnr2msBgbMhP7Jyg0gzKiB8O7NF9TAnqNuVAhUlg2YgEQ5m9k+kqcqTGzUoef/qSr6D150h3zFonHN83vhg11IaIoeRggIbvHZmgDDSs63sy8VBf/9OQ8gRQs0zyotyIbRpBlrcztymh7KMLlmj0="
  app: villoro-devops
