language: python

python:
- '3.6'

install:
- pip install -r requirements.txt
- pip install codecov

script:
- nosetests --with-coverage --cover-package=src

after_success:
- codecov

deploy:
  provider: heroku
  api_key:
    secure: b82QTzOh+m3PKr1Rotyj4qWs0M0yiJOXTWizq6oGJSfmAHWCTtetlVN+nSKyd9zvf1GmuhWk1/DdEFkDQMr0O7g5R8Y8B8BjMug14wyRqK3HMqA8Pc0Js+UAjHrQfhoYz5XaWjl4QyqNCotOrnS21Vu8h+XQjqIrhQaSgehvD8JC8qo7X6Re2n6hq1kT1hdnRNO5K5/xSBLcmnp7UYrhyE6/dCPm201pCFBpfOBje3HHMyB8t4K+JaxW0xXQtCxjxmSlsLAZt1D0Z2sZNk7E9DsYwgdiZ90HXzgBVFmvyd4u/wmoaestON1MWWY4G7nX9I2NZvDS3TwJ9mP7YSiu69nCXK6ZhcatTO+tp0k3EN46uPy8EuBVRU408X8d72HoCpiIg2T7kUG4FwEBVH62LUGC7AR9q3RCY/iwZ0Ngtyuv0Cx219coAdQG1srEDeNeMdTKIfF11efayC2ZfkKxLYs3PLh7gQ16puMxkqbiMQ0Kj2vAfoJyX+Qw9QEtxZ4xmVC0Ypoo1bnpWAin07TbcsBAwTStVFmoOLDDtjREIIu8AO0Noh+jvMmfwvGiT1fy4B+JV2orLIYwTC1zGdSS1WVtLQtNoilEi1xvUCsiGDMG4PFK94j9zFSxXJCy2oCK88L5psDq5Cchxfuv3PM3CO9wRCKYMMxHRerDc6qRXAc=
  app: villoro-devops
  on:
    repo: villoro/devops
